### ISSUE TITLE
Solving env

### ISSUE THREAD

**Issue by xperrylinn** [openforcefield/openff-toolkit#1625]
**Describe the bug**

Howdy! `openff-toolkit` is a dependency in my repository where I've tried to set up a GitHub action for running tests. The action keeps failing at the install dependencies step and it appears to be because of `openff-toolkit` taking a long time to solve the environment. I've included a screen capture below which is an example of the failure that I'm seeing. In the screen capture, I pinned a specific version of `openff-toolkit` and I've tried the latest version and still have the same issue. I did encounter a few builds where it succeeded, but dozens of attempts have failed. When I create the environment locally with `openff-toolkit`, it takes about 15 minutes, but eventually works, so this made me think maybe it was a GitHub action issue to which I've made a [post](https://github.com/orgs/community/discussions/56709) asking for help, but no luck yet. 

![Screenshot 2023-05-30 at 9 04 38 PM](https://github.com/openforcefield/openff-toolkit/assets/25185558/de82b197-db82-4d0c-b2ae-dcbf36a76c98)

Any suggestion on how to proceed? For reference here is a link to my [python.yaml](https://github.com/xperrylinn/atomate2-openmm/blob/95ad7642c13a7528fcf7176c523cec64d0fb14f1/.github/workflows/python.yaml) GitHub action build file.

**To Reproduce**

**Output**

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list`

**Additional context**

**Comment by Yoshanuikabundi** [comment]
Yeah Conda can be very slow with large environments. We recommend using Mamba, which does the same thing but with much faster dependency resolution. You can use their [`mamba-org/setup-micromamba`](https://github.com/mamba-org/setup-micromamba) action instead of `conda-incubator/setup-miniconda` (which might take a bit of settings-tweaking to switch to), and then just replace `conda` with `mamba` at the CLI and it'll work the same but faster. We have [detailed instructions](https://docs.openforcefield.org/en/latest/install.html) for how to do that locally - once you're at the CLI, Mamba is a drop-in replacement for Conda.

I'd also suggest installing everything at once, rather than one package at a time, because it'll avoid a situation where:
1. Package A requires dependency X>0.3.0, so the latest version of X (say, v0.6.0) is downloaded and installed
2. Package B requires dependency X<0.5.0, so X must be downgraded to v0.4.0 (and therefore is redownloaded)

I think setup-micromamba might actually require putting everything in an environment, so that'd just look something like:

environment.yaml:
```yaml
name: test
channels:
  - conda-forge
dependencies:
  - python==3.9
  - openmm==8.0.0
  - openff-toolkit
  - MDAnalysis==2.4.3
  - atomate2==0.0.10
  - jobflow==0.1.11
  - pip:
    - git+https://github.com/orionarcher/pymatgen-io-openmm.git
    - pytest
    - pytest-cov
    - pandas
```

(One nice thing about this is that you can install it locally with `mamba create --file environment.yaml`)

python.yaml:
```yaml
name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: <path/to/environment.yaml>
          cache-environment: true
          init-shell: >-
            bash
            powershell
      - name: Install project
        shell: bash -l {0}
        run: |
          pip install .
      - shell: bash -l {0}
        run: |
          mamba info
          mamba list
      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest
```

Hope this helps!
